services:
  soft-serve:
    build:
      context: .
      dockerfile: Dockerfile
    image: headquarters
    container_name: soft-serve
    volumes:
      - ./bootstrap:/bootstrap
    working_dir: /home/skogix
    stdin_open: true
    tty: true
    restart: "no"
